const planTasks = [
  { id: "T01", title: "Analyze existing authentication architecture", phase: "Analysis", status: "done" },
  { id: "T02", title: "Design OAuth backend flow", phase: "Design", status: "done" },
  { id: "T03", title: "Design login UI", phase: "Design", status: "done" },
  { id: "T04", title: "Implement OAuth backend", phase: "Implementation", status: "running" },
  { id: "T05", title: "Implement login UI", phase: "Implementation", status: "running" },
  { id: "T06", title: "Integration", phase: "Integration", status: "queued" },
  { id: "T07", title: "Security & code review", phase: "Review", status: "queued" },
  { id: "T08", title: "Final verification", phase: "Verify", status: "queued" },
]

const criteria = [
  "Google OAuth login flow completes successfully end-to-end",
  "Existing email/password login continues to work",
  "Invalid or expired OAuth callbacks are rejected with clear errors",
  "OAuth tokens are never stored in plaintext",
  "All authentication tests pass (48/48)",
  "Security review passes with no high-severity findings",
]

const risks = [
  { level: "Low", text: "Session architecture changes may require existing tests to be updated." },
  { level: "Medium", text: "OAuth state validation must be implemented correctly to prevent CSRF attacks." },
]

export default function PlanView() {
  return (
    <div className="h-full overflow-y-auto px-6 py-6">
      <div className="max-w-3xl mx-auto">
        <div className="bg-surface border border-line rounded-xl p-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-base font-semibold text-fore">Implementation Plan</h2>
            <div className="flex items-center gap-2">
              <span className="text-[10px] px-2 py-1 rounded bg-ok-muted text-ok font-medium">
                Approved · Executing
              </span>
              <span className="text-[10px] text-faint">Generated by Architect · Claude Opus</span>
            </div>
          </div>

          {/* Goal */}
          <div className="mb-5">
            <h3 className="text-[10px] font-semibold text-faint uppercase tracking-widest mb-2">
              Goal
            </h3>
            <p className="text-sm text-dim leading-relaxed">
              Implement Google OAuth login that integrates with the existing session architecture
              without breaking current authentication flows.
            </p>
          </div>

          {/* Technical approach */}
          <div className="mb-5">
            <h3 className="text-[10px] font-semibold text-faint uppercase tracking-widest mb-2">
              Technical approach
            </h3>
            <p className="text-sm text-dim leading-relaxed">
              Use the Passport.js Google OAuth 2.0 strategy. The callback will create or update a
              user record and establish a session using the existing session management layer. All
              tokens will be hashed with bcrypt before any storage. State parameter validation will
              prevent CSRF.
            </p>
          </div>

          {/* Task breakdown */}
          <div className="mb-5">
            <h3 className="text-[10px] font-semibold text-faint uppercase tracking-widest mb-3">
              Task breakdown
            </h3>
            <div className="space-y-0 border border-line rounded-lg overflow-hidden">
              {planTasks.map((task, i) => (
                <div
                  key={task.id}
                  className={`flex items-center gap-3 px-4 py-2.5 ${
                    i < planTasks.length - 1 ? "border-b border-line" : ""
                  } ${task.status === "running" ? "bg-accent-muted" : ""}`}
                >
                  <span className="text-[11px] font-mono text-faint w-7 shrink-0">{task.id}</span>
                  <span
                    className={`flex-1 text-sm ${
                      task.status === "done"
                        ? "text-faint line-through"
                        : task.status === "running"
                        ? "text-fore"
                        : "text-dim"
                    }`}
                  >
                    {task.title}
                  </span>
                  <span className="text-[10px] text-faint shrink-0">{task.phase}</span>
                  <span
                    className={`text-[10px] px-1.5 py-0.5 rounded font-medium shrink-0 ${
                      task.status === "done"
                        ? "bg-ok-muted text-ok"
                        : task.status === "running"
                        ? "bg-accent-muted text-accent"
                        : "bg-elevated text-faint"
                    }`}
                  >
                    {task.status}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Dependencies */}
          <div className="mb-5">
            <h3 className="text-[10px] font-semibold text-faint uppercase tracking-widest mb-3">
              Dependencies
            </h3>
            <div className="bg-base border border-line rounded-lg p-4 font-mono text-xs text-dim space-y-1">
              <div>T04 depends on T02</div>
              <div>T05 depends on T03</div>
              <div>T06 depends on T04, T05</div>
              <div>T07 depends on T06</div>
              <div>T08 depends on T07</div>
            </div>
          </div>

          {/* Acceptance criteria */}
          <div className="mb-5">
            <h3 className="text-[10px] font-semibold text-faint uppercase tracking-widest mb-3">
              Acceptance criteria
            </h3>
            <ul className="space-y-2">
              {criteria.map((c) => (
                <li key={c} className="flex items-start gap-2 text-sm text-dim">
                  <svg width="13" height="13" viewBox="0 0 13 13" fill="none" className="mt-0.5 shrink-0 text-line">
                    <rect x="1" y="1" width="11" height="11" rx="2" stroke="currentColor" strokeWidth="1.25" />
                  </svg>
                  {c}
                </li>
              ))}
            </ul>
          </div>

          {/* Risks */}
          <div className="mb-6">
            <h3 className="text-[10px] font-semibold text-faint uppercase tracking-widest mb-3">
              Risks
            </h3>
            <div className="space-y-2">
              {risks.map((r) => (
                <div key={r.text} className="flex items-start gap-2 p-3 bg-base rounded-lg border border-line">
                  <span
                    className={`text-[10px] px-1.5 py-0.5 rounded font-medium shrink-0 mt-0.5 ${
                      r.level === "Medium" ? "bg-warn-muted text-warn" : "bg-elevated text-faint"
                    }`}
                  >
                    {r.level}
                  </span>
                  <span className="text-sm text-dim">{r.text}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-2 pt-4 border-t border-line">
            <button className="px-4 py-2 text-sm font-medium bg-elevated hover:bg-hover text-dim hover:text-fore border border-line rounded-lg transition-colors">
              Edit plan
            </button>
            <button className="px-4 py-2 text-sm font-medium text-faint hover:text-dim border border-line rounded-lg transition-colors">
              Regenerate
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
