import { readFileSync, writeFileSync } from 'node:fs'
const CRLF = '\r\n'
const path = 'tests/unit/chatgpt-web-browser-worker.test.ts'
let content = readFileSync(path, 'utf8')
const oldEnd = `  it('aborts and closes the page when the signal fires', async () => {${CRLF}    const controller = new AbortController()${CRLF}    controller.abort()${CRLF}    const page = fakePage({ snapshots: [{ hasStopButton: true, hasCopyButton: false, text: '' }] })${CRLF}    await expect(${CRLF}      runChatGptWebTurn(page, async () => page, 'hello', CHATGPT_WEB_EFFORT_LEVELS[0], controller.signal, { pollIntervalMs: 0 })${CRLF}    ).rejects.toThrow(/abort/i)${CRLF}    expect(page.close).toHaveBeenCalled()${CRLF}  })${CRLF}})`
const newBlock = `  it('falls back to recreate(visible) and calls onFallback when Cloudflare challenge detected', async () => {${CRLF}    const failingPage: ChatGptWebPage = {${CRLF}      goto: vi.fn(async () => undefined),${CRLF}      waitForSelector: vi.fn(async () => { throw new Error('Timeout 30000ms exceeded') }),${CRLF}      click: vi.fn(async () => undefined),${CRLF}      insertText: vi.fn(async () => undefined),${CRLF}      readDialogText: vi.fn(async () => null),${CRLF}      readSnapshot: vi.fn(async () => ({ hasStopButton: false, hasCopyButton: false, text: '' })),${CRLF}      title: vi.fn(async () => 'Just a moment...'),${CRLF}      url: vi.fn(() => 'https://chatgpt.com/'),${CRLF}      close: vi.fn(async () => undefined)${CRLF}    }${CRLF}    const visiblePage = fakePage({ snapshots: [{ hasStopButton: false, hasCopyButton: true, text: 'Answer' }] })${CRLF}    const recreate = vi.fn(async (mode: string) => {${CRLF}      expect(mode).toBe('visible')${CRLF}      return visiblePage${CRLF}    })${CRLF}    const onFallback = vi.fn()${CRLF}    const result = await runChatGptWebTurn(failingPage, recreate, 'hello', CHATGPT_WEB_EFFORT_LEVELS[0], undefined, { pollIntervalMs: 0, onFallback })${CRLF}    expect(recreate).toHaveBeenCalledWith('visible')${CRLF}    expect(onFallback).toHaveBeenCalledWith('cloudflare')${CRLF}    expect(failingPage.close).toHaveBeenCalled()${CRLF}    expect(result).toBe('Answer')${CRLF}  })${CRLF}${CRLF}  it('throws Vietnamese [bs] error when redirected to /auth/login', async () => {${CRLF}    const failingPage: ChatGptWebPage = {${CRLF}      goto: vi.fn(async () => undefined),${CRLF}      waitForSelector: vi.fn(async () => { throw new Error('Timeout 30000ms exceeded') }),${CRLF}      click: vi.fn(async () => undefined),${CRLF}      insertText: vi.fn(async () => undefined),${CRLF}      readDialogText: vi.fn(async () => null),${CRLF}      readSnapshot: vi.fn(async () => ({ hasStopButton: false, hasCopyButton: false, text: '' })),${CRLF}      title: vi.fn(async () => 'Log in'),${CRLF}      url: vi.fn(() => 'https://chatgpt.com/auth/login'),${CRLF}      close: vi.fn(async () => undefined)${CRLF}    }${CRLF}    await expect(${CRLF}      runChatGptWebTurn(failingPage, async () => failingPage, 'hello', CHATGPT_WEB_EFFORT_LEVELS[0], undefined, { pollIntervalMs: 0 })${CRLF}    ).rejects.toThrow(/\[bs\] Phiên đăng nhập/)${CRLF}  })${CRLF}${CRLF}  it('aborts and closes the page when the signal fires', async () => {${CRLF}    const controller = new AbortController()${CRLF}    controller.abort()${CRLF}    const page = fakePage({ snapshots: [{ hasStopButton: true, hasCopyButton: false, text: '' }] })${CRLF}    await expect(${CRLF}      runChatGptWebTurn(page, async () => page, 'hello', CHATGPT_WEB_EFFORT_LEVELS[0], controller.signal, { pollIntervalMs: 0 })${CRLF}    ).rejects.toThrow(/abort/i)${CRLF}    expect(page.close).toHaveBeenCalled()${CRLF}  })${CRLF}})`
if (!content.includes(oldEnd)) { console.error('END NOT FOUND'); process.exit(1) }
content = content.replace(oldEnd, newBlock)
writeFileSync(path, content)
console.log('OK')